const S3_MAX_KEYS = 1000;
const CONFIGURED_BROWSE_WINDOW_LIMIT = 5000;

if (CONFIGURED_BROWSE_WINDOW_LIMIT < S3_MAX_KEYS) {
  throw new Error(`BROWSE_WINDOW_LIMIT must be at least ${S3_MAX_KEYS}.`);
}

if (CONFIGURED_BROWSE_WINDOW_LIMIT % S3_MAX_KEYS !== 0) {
  throw new Error(`BROWSE_WINDOW_LIMIT must be a multiple of ${S3_MAX_KEYS}.`);
}

export const BROWSE_WINDOW_LIMIT = CONFIGURED_BROWSE_WINDOW_LIMIT;
