#!/usr/bin/env bun
import { readdirSync, statSync, writeFileSync, existsSync } from 'fs';
import { join, relative, extname } from 'path';
import { createHash } from 'crypto';

const PROJECT_ROOT = join(import.meta.dir, '..');
const DIST_DIR = join(PROJECT_ROOT, 'dist');
const OUTPUT = join(PROJECT_ROOT, 'server', 'cli', 'embeddedAssets.generated.ts');

const MIME: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js':   'application/javascript; charset=utf-8',
  '.mjs':  'application/javascript; charset=utf-8',
  '.css':  'text/css; charset=utf-8',
  '.svg':  'image/svg+xml',
  '.json': 'application/json; charset=utf-8',
  '.map':  'application/json; charset=utf-8',
  '.txt':  'text/plain; charset=utf-8',
  '.ico':  'image/x-icon',
};

function walk(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

function toIdent(url: string): string {
  // Sanitized prefix is human-readable; sha1 suffix of the full URL guarantees
  // uniqueness even when the prefix would collide (e.g. "/foo-bar" vs "/foo_bar").
  const sanitized = url.replace(/[^a-zA-Z0-9]/g, '_').replace(/^_+/, '');
  const prefix = sanitized.slice(0, 32);
  const hash = createHash('sha1').update(url).digest('hex').slice(0, 8);
  return `a_${prefix}_${hash}`;
}

if (!existsSync(DIST_DIR)) {
  console.error(`generate-embedded-assets: ${DIST_DIR} not found. Run build:client first.`);
  process.exit(1);
}

const files = walk(DIST_DIR).sort();
if (files.length === 0) {
  console.error(`generate-embedded-assets: ${DIST_DIR} is empty.`);
  process.exit(1);
}

const importLines: string[] = [];
const entryLines: string[] = [];

for (const full of files) {
  const ext = extname(full).toLowerCase();
  const mime = MIME[ext];
  if (!mime) {
    console.error(
      `generate-embedded-assets: unknown MIME for ${relative(PROJECT_ROOT, full)} ` +
      `(extension "${ext}"). Add it to the MIME table in scripts/generate-embedded-assets.ts.`
    );
    process.exit(1);
  }
  const url = '/' + relative(DIST_DIR, full).split('\\').join('/');
  // Import path is relative to the generated file (server/cli/embeddedAssets.generated.ts).
  const importPath = '../../' + relative(PROJECT_ROOT, full).split('\\').join('/');
  const ident = toIdent(url);
  importLines.push(`import ${ident} from ${JSON.stringify(importPath)} with { type: 'text' };`);
  entryLines.push(`  ${JSON.stringify(url)}: { content: ${ident} as string, mime: ${JSON.stringify(mime)} },`);
}

const out = [
  '// AUTO-GENERATED by scripts/generate-embedded-assets.ts',
  '// Do not edit. Regenerated on every standalone build.',
  '',
  ...importLines,
  '',
  'export const embeddedAssets: Record<string, { content: string; mime: string }> = {',
  ...entryLines,
  '};',
  '',
].join('\n');

writeFileSync(OUTPUT, out);
console.log(`generate-embedded-assets: wrote ${relative(PROJECT_ROOT, OUTPUT)} (${files.length} assets)`);
